version: "3.8"

services:
    php-env:
      build: .
      volumes: 
      - ./src:/var/www/html
      ports:
      - 8000:80

    mysql_db:
      container_name: mysql_db
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1